# Generated by Django 5.0.6 on 2024-07-03 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0004_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='birth_date',
        ),
        migrations.RemoveField(
            model_name='user',
            name='phone_number',
        ),
        migrations.AddField(
            model_name='user',
            name='bio',
            field=models.CharField(default='', max_length=256),
            preserve_default=False,
        ),
    ]
