# Generated by Django 5.0.6 on 2024-07-05 07:58

from django.db import migrations, transaction
from decimal import Decimal


def populate_position_for_card_model(apps, schema_editor):
    Card = apps.get_model("task", "Card")
    lists = Card.objects.values_list("list", flat=True).distinct()

    with transaction.atomic():
        for list in lists:
            cards_in_list = Card.objects.filter(list=list).order_by("id")
            position = 100

            for card_instance in cards_in_list:
                card_instance.position = Decimal(position)
                card_instance.save()
                position += 100


def populate_position_for_list_model(apps, schema_editor):
    List = apps.get_model("task", "List")
    boards = List.objects.values_list("board", flat=True).distinct()

    with transaction.atomic():
        for board in boards:
            lists_in_board = List.objects.filter(board=board).order_by("id")
            position = 100

            for list_instance in lists_in_board:
                list_instance.position = Decimal(position)
                list_instance.save()
                position += 100


class Migration(migrations.Migration):

    dependencies = [
        ("task", "0007_card_created_at_card_position_list_position"),
    ]

    operations = [
        migrations.RunPython(populate_position_for_card_model),
        migrations.RunPython(populate_position_for_list_model),
    ]
