# Generated by Django 5.0.6 on 2024-07-09 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0010_alter_card_position_alter_list_position'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='position',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='list',
            name='position',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
