# Generated by Django 5.0.6 on 2024-07-09 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0012_auto_20240709_0132'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='title',
            field=models.CharField(default='Card title', max_length=256),
            preserve_default=False,
        ),
    ]
