# Generated by Django 5.0.6 on 2024-07-09 11:59

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0013_card_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='members',
            field=models.ManyToManyField(related_name='cards', to=settings.AUTH_USER_MODEL),
        ),
    ]
