# Generated by Django 5.0.6 on 2024-07-18 08:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0017_rename_upload_document_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attachment',
            name='card',
        ),
    ]
