# Generated by Django 5.0.6 on 2024-07-18 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0019_alter_attachment_file_remove_card_attachments_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='attachment',
            name='title',
            field=models.CharField(blank=True, max_length=256),
        ),
    ]
