# Generated by Django 5.0.6 on 2024-07-25 10:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0020_attachment_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='board',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='notificaitons', to='task.board'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='card',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='task.card'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='list',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='notificaitons', to='task.list'),
        ),
    ]
