# Generated by Django 5.0.6 on 2024-07-25 10:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0021_alter_notification_board_alter_notification_card_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='board',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notificaitons', to='task.board'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='card',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='task.card'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='list',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notificaitons', to='task.list'),
        ),
    ]
