# Generated by Django 5.0.6 on 2024-07-27 09:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0024_rename_user_notification_recipient_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Label',
        ),
        migrations.DeleteModel(
            name='Project',
        ),
    ]
